# Generated by Django 4.2 on 2023-05-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='', max_length=11),
        ),
    ]
